'use client';

import { useState, useCallback } from 'react';
import {
  collection,
  addDoc,
  updateDoc,
  doc,
  query,
  where,
  getDocs,
  serverTimestamp,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase';
import type { TaskReview, TaskSubmission } from '@/lib/types';
import { handleError, logError } from '@/utils/error-handler';

export function useTaskReview() {
  const firestore = useFirestore();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Submit a task for AI review
   */
  const submitTaskForReview = useCallback(
    async (submissionData: Omit<TaskSubmission, 'id' | 'submittedAt'>) => {
      if (!firestore) {
        setError('Firestore not initialized');
        return null;
      }

      setLoading(true);
      setError(null);

      try {
        const submissionsRef = collection(firestore, 'taskSubmissions');
        const docRef = await addDoc(submissionsRef, {
          ...submissionData,
          submittedAt: serverTimestamp(),
          status: 'submitted',
        });

        return docRef.id;
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return null;
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get task submissions for a mentor to review
   */
  const getMentorReviewQueue = useCallback(
    async (mentorId: string): Promise<TaskSubmission[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        // For now, get all pending submissions
        // In a real app, this would be based on course assignments
        const q = query(
          collection(firestore, 'taskSubmissions'),
          where('status', '==', 'submitted')
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskSubmission));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Save task review generated by AI
   */
  const saveTaskReview = useCallback(
    async (
      submissionId: string,
      mentorId: string,
      mentorName: string,
      studentId: string,
      taskId: string,
      reviewData: {
        knowledgeGaps: string;
        targetedFeedback: string;
        overallAssessment: string;
        rating: number;
      }
    ) => {
      if (!firestore) {
        setError('Firestore not initialized');
        return null;
      }

      setLoading(true);
      setError(null);

      try {
        // Save review
        const reviewsRef = collection(firestore, 'taskReviews');
        const reviewRef = await addDoc(reviewsRef, {
          submissionId,
          taskId,
          mentorId,
          mentorName,
          studentId,
          knowledgeGaps: reviewData.knowledgeGaps,
          targetedFeedback: reviewData.targetedFeedback,
          overallAssessment: reviewData.overallAssessment,
          rating: reviewData.rating,
          isPeerReviewed: false,
          reviewedAt: serverTimestamp(),
          createdAt: serverTimestamp(),
        });

        // Update submission status
        const submissionRef = doc(firestore, 'taskSubmissions', submissionId);
        await updateDoc(submissionRef, {
          status: 'reviewed',
        });

        return reviewRef.id;
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return null;
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get reviews for a specific submission
   */
  const getSubmissionReviews = useCallback(
    async (submissionId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('submissionId', '==', submissionId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get all reviews created by a mentor
   */
  const getMentorReviews = useCallback(
    async (mentorId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('mentorId', '==', mentorId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get reviews for a student
   */
  const getStudentReviews = useCallback(
    async (studentId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('studentId', '==', studentId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  return {
    loading,
    error,
    submitTaskForReview,
    getMentorReviewQueue,
    saveTaskReview,
    getSubmissionReviews,
    getMentorReviews,
    getStudentReviews,
  };
}
