'use client';

import { useState, useCallback } from 'react';
import {
  collection,
  addDoc,
  updateDoc,
  doc,
  query,
  where,
  getDocs,
  serverTimestamp,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase';
import type { TaskReview, TaskSubmission } from '@/lib/types';
import { handleError, logError } from '@/utils/error-handler';

export function useTaskReview() {
  const firestore = useFirestore();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Submit a task for AI review
   */
  const submitTaskForReview = useCallback(
    async (submissionData: Omit<TaskSubmission, 'id' | 'submittedAt'>) => {
      if (!firestore) {
        setError('Firestore not initialized');
        return null;
      }

      setLoading(true);
      setError(null);

      try {
        const submissionsRef = collection(firestore, 'taskSubmissions');
        const docRef = await addDoc(submissionsRef, {
          ...submissionData,
          submittedAt: serverTimestamp(),
          status: 'submitted',
        });

        return docRef.id;
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return null;
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get task submissions for a mentor to review
   * Only shows submissions for tasks in the mentor's courses
   */
  const getMentorReviewQueue = useCallback(
    async (mentorId: string): Promise<TaskSubmission[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        // Step 1: Get all courses owned by this mentor
        const coursesQuery = query(
          collection(firestore, 'courses'),
          where('ownerId', '==', mentorId)
        );
        const coursesSnapshot = await getDocs(coursesQuery);
        const courseIds = coursesSnapshot.docs.map(doc => doc.id);

        if (courseIds.length === 0) {
          console.log('[getMentorReviewQueue] Mentor has no courses');
          return [];
        }

        console.log('[getMentorReviewQueue] Found courses:', courseIds);

        // Step 2: Get all submitted tasks for those courses
        const tasksQuery = query(
          collection(firestore, 'tasks'),
          where('courseId', 'in', courseIds)
        );
        const tasksSnapshot = await getDocs(tasksQuery);
        const taskIds = tasksSnapshot.docs.map(doc => doc.id);

        if (taskIds.length === 0) {
          console.log('[getMentorReviewQueue] No tasks in mentor courses');
          return [];
        }

        console.log('[getMentorReviewQueue] Found tasks:', taskIds);

        // Step 3: Get all submissions for those tasks with 'submitted' status
        const submissionsQuery = query(
          collection(firestore, 'taskSubmissions'),
          where('status', '==', 'submitted')
        );
        const submissionsSnapshot = await getDocs(submissionsQuery);

        // Filter submissions to only those for the mentor's tasks
        const mentorSubmissions = submissionsSnapshot.docs
          .filter(doc => taskIds.includes(doc.data().taskId))
          .map((doc) => {
            const data = doc.data();
            return {
              id: doc.id,
              taskId: data.taskId,
              courseId: data.courseId,
              studentId: data.studentId,
              studentName: data.studentName || 'Unknown',
              code: data.code,
              notes: data.notes,
              submittedAt: data.submittedAt,
              status: data.status,
              // For backward compatibility with old field names
              submissionText: data.code,
              submissionCode: data.code,
              studentEmail: data.studentEmail || '',
            } as TaskSubmission;
          });

        console.log('[getMentorReviewQueue] Found submissions:', mentorSubmissions.length);
        return mentorSubmissions;
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        console.error('[getMentorReviewQueue] Error:', err);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Save task review generated by AI
   */
  const saveTaskReview = useCallback(
    async (
      submissionId: string,
      mentorId: string,
      mentorName: string,
      studentId: string,
      taskId: string,
      reviewData: {
        knowledgeGaps: string;
        targetedFeedback: string;
        overallAssessment: string;
        rating: number;
      }
    ) => {
      if (!firestore) {
        setError('Firestore not initialized');
        return null;
      }

      setLoading(true);
      setError(null);

      try {
        // Save review
        const reviewsRef = collection(firestore, 'taskReviews');
        const reviewRef = await addDoc(reviewsRef, {
          submissionId,
          taskId,
          mentorId,
          mentorName,
          studentId,
          knowledgeGaps: reviewData.knowledgeGaps,
          targetedFeedback: reviewData.targetedFeedback,
          overallAssessment: reviewData.overallAssessment,
          rating: reviewData.rating,
          isPeerReviewed: false,
          reviewedAt: serverTimestamp(),
          createdAt: serverTimestamp(),
        });

        // Update submission status
        const submissionRef = doc(firestore, 'taskSubmissions', submissionId);
        await updateDoc(submissionRef, {
          status: 'reviewed',
        });

        return reviewRef.id;
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return null;
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get reviews for a specific submission
   */
  const getSubmissionReviews = useCallback(
    async (submissionId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('submissionId', '==', submissionId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get all reviews created by a mentor
   */
  const getMentorReviews = useCallback(
    async (mentorId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('mentorId', '==', mentorId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  /**
   * Get reviews for a student
   */
  const getStudentReviews = useCallback(
    async (studentId: string): Promise<TaskReview[]> => {
      if (!firestore) {
        setError('Firestore not initialized');
        return [];
      }

      setLoading(true);
      setError(null);

      try {
        const q = query(
          collection(firestore, 'taskReviews'),
          where('studentId', '==', studentId)
        );
        const snapshot = await getDocs(q);

        return snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        } as TaskReview));
      } catch (err) {
        const appError = handleError(err);
        logError(appError);
        setError(appError.message);
        return [];
      } finally {
        setLoading(false);
      }
    },
    [firestore]
  );

  return {
    loading,
    error,
    submitTaskForReview,
    getMentorReviewQueue,
    saveTaskReview,
    getSubmissionReviews,
    getMentorReviews,
    getStudentReviews,
  };
}
